import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st
import plotly.graph_objects as go

# Set page configurations
st.set_page_config(
    page_title="Wi-Fi Intruder Detector",
    page_icon="🔒",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Feature columns used by the classifier (must match training order)
FEATURE_COLUMNS = [
    'packet_count',
    'avg_packet_size',
    'max_packet_size',
    'min_packet_size',
    'tcp_count',
    'udp_count',
    'total_bytes',
    'tcp_udp_ratio',
    'avg_inter_arrival_time'
]

# Load model and label encoder with st.cache_resource
@st.cache_resource
def load_ml_assets():
    model_path = os.path.join('model', 'device_classifier.pkl')
    encoder_path = os.path.join('model', 'label_encoder.pkl')
    
    if not os.path.exists(model_path) or not os.path.exists(encoder_path):
        return None, None
        
    try:
        model = joblib.load(model_path)
        label_encoder = joblib.load(encoder_path)
        return model, label_encoder
    except Exception as e:
        st.sidebar.error(f"Error loading model files: {e}")
        return None, None

# Load assets
model, label_encoder = load_ml_assets()

# Sidebar Layout
st.sidebar.title("🛠️ Settings & Config")
st.sidebar.markdown("---")

# Data Source Selection
data_source = st.sidebar.radio(
    "Data Source",
    ["Upload CSV", "Use Default Dataset (dataset/wifi_dataset.csv)"],
    index=1 if os.path.exists(os.path.join('dataset', 'wifi_dataset.csv')) else 0
)

uploaded_file = None
if data_source == "Upload CSV":
    uploaded_file = st.sidebar.file_uploader(
        "Upload extracted features CSV",
        type=["csv"],
        help="Upload the features CSV file generated by Phase 1 extraction or similar format."
    )

# Confidence Slider
threshold = st.sidebar.slider(
    "Detection Threshold",
    min_value=0.50,
    max_value=1.00,
    value=0.70,
    step=0.05,
    help="Confidence threshold below which a device is flagged as Unknown/Intruder."
)

st.sidebar.markdown("---")
st.sidebar.subheader("About")
st.sidebar.info(
    "**Wi-Fi Intruder Detector**\n\n"
    "This dashboard performs device classification and intrusion detection using network traffic fingerprinting. "
    "Features extracted from network packet captures (.pcapng) are evaluated by a Random Forest classifier. "
    "If the prediction confidence drops below the threshold, the device is flagged as an unauthorized intruder."
)

# Main Dashboard Header
st.title("🔒 Wi-Fi Intruder Detector")
st.subheader("Network Traffic Fingerprinting Dashboard")
st.markdown("---")

# Verify model assets
if model is None or label_encoder is None:
    st.error("❌ Model assets not found. Please run 'python scripts/train_model.py' first.")
    st.stop()

# Helper predict function accepting a dataframe row
def predict_device_row(row: pd.Series, model, label_encoder, threshold: float) -> dict:
    # Convert series to DataFrame with exact column order
    df_row = pd.DataFrame([row])[FEATURE_COLUMNS]
    
    # Run prediction probabilities
    probabilities = model.predict_proba(df_row)[0]
    
    # Get max confidence and predicted class
    max_idx = np.argmax(probabilities)
    confidence = float(probabilities[max_idx])
    decoded_label = label_encoder.inverse_transform([max_idx])[0]
    
    is_unknown = confidence < threshold
    predicted_label = "Unknown Device Detected" if is_unknown else decoded_label
    
    return {
        "predicted_label": predicted_label,
        "confidence": confidence,
        "is_unknown": is_unknown,
        "original_label": decoded_label
    }

# App behavior based on data source
df = None
if data_source == "Upload CSV":
    if uploaded_file is not None:
        try:
            df = pd.read_csv(uploaded_file)
        except Exception as e:
            st.error(f"Error reading uploaded CSV file: {e}")
            st.stop()
    else:
        st.info("👋 Welcome! Please upload a features CSV file in the sidebar to get started.")
        st.markdown("""
        ### Quick Start Guide
        1. Run feature extraction on your `.pcapng` files to generate a dataset:
           ```bash
           python scripts/extract_features.py
           ```
        2. Upload the output dataset CSV file (usually found at `dataset/wifi_dataset.csv`) using the sidebar.
        3. Explore the **Device Prediction** and **Traffic Statistics** tabs.
        4. Fine-tune the **Detection Threshold** in the sidebar to flag anomalous or low-confidence devices.
        """)
        st.stop()
else:
    default_path = os.path.join('dataset', 'wifi_dataset.csv')
    if os.path.exists(default_path):
        try:
            df = pd.read_csv(default_path)
        except Exception as e:
            st.error(f"Error reading default dataset CSV: {e}")
            st.stop()
    else:
        st.error(f"❌ Default dataset not found at `{default_path}`. Please upload a CSV instead.")
        st.stop()

# Once df is successfully loaded, verify columns
if df is not None:
    missing_cols = [col for col in FEATURE_COLUMNS if col not in df.columns]
    if missing_cols:
        st.error(f"The loaded dataset is missing required feature columns: {missing_cols}")
        st.stop()
        
    # Set up Tabs
    tab_pred, tab_stats = st.tabs(["🎯 Device Prediction", "📊 Traffic Statistics"])
    
    # --- Tab 1: Device Prediction ---
    with tab_pred:
        st.subheader("Data Preview (First 5 Rows)")
        st.dataframe(df.head(5), use_container_width=True)
        st.markdown("---")
        
        st.subheader("Classification & Intrusion Alerts")
        
        # Run prediction on all rows
        results = []
        for idx, row in df.iterrows():
            pred_res = predict_device_row(row, model, label_encoder, threshold)
            
            # Determine source filename identifier
            source_file = row['source_file'] if 'source_file' in df.columns else f"Session {idx + 1}"
            
            results.append({
                "source_file": source_file,
                "predicted_label": pred_res["predicted_label"],
                "confidence %": f"{pred_res['confidence'] * 100:.2f}%",
                "is_unknown": pred_res["is_unknown"],
                "confidence_val": pred_res['confidence']
            })
            
        results_df = pd.DataFrame(results)
        
        # Calculate summary statistics
        total_scanned = len(results_df)
        unknown_alerts = int(results_df['is_unknown'].sum())
        known_devices = total_scanned - unknown_alerts
        
        # Display Metrics Summary cards
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Total Sessions Scanned", total_scanned)
        with col2:
            st.metric("Authorized Devices", known_devices)
        with col3:
            # Highlight intruder alerts in red if present
            if unknown_alerts > 0:
                st.metric("Intruder Alerts ⚠️", unknown_alerts, delta=f"+{unknown_alerts} Unknown", delta_color="inverse")
            else:
                st.metric("Intruder Alerts ⚠️", unknown_alerts)
                
        st.markdown("---")
        
        # Display results table
        st.markdown("#### Prediction Results Table")
        display_cols = ["source_file", "predicted_label", "confidence %", "is_unknown"]
        st.dataframe(results_df[display_cols], use_container_width=True)
        
        # Show success / error messages for each session
        st.markdown("#### Alert Feed")
        for res in results:
            label_text = f"**{res['source_file']}**: Classified as **{res['predicted_label']}** with **{res['confidence %']}** confidence."
            if res['is_unknown']:
                st.error(label_text, icon="⚠️")
            else:
                st.success(label_text, icon="✅")
                
    # --- Tab 2: Traffic Statistics ---
    with tab_stats:
        st.subheader("Network Traffic Fingerprint Analytics")
        st.write("Compare packets, bytes, and protocols across all recorded sessions.")
        
        # Ensure source_file or index is set as the session label
        sessions = df['source_file'] if 'source_file' in df.columns else [f"Session {i+1}" for i in range(len(df))]
        
        # Plot 1: Packet count per session
        fig_packets = go.Figure(
            data=[go.Bar(
                x=sessions,
                y=df['packet_count'],
                marker_color='royalblue',
                name='Packets'
            )]
        )
        fig_packets.update_layout(
            title="Total Packet Count per Session",
            xaxis_title="Session / File Name",
            yaxis_title="Packet Count",
            template="plotly_dark",
            margin=dict(l=40, r=40, t=60, b=100)
        )
        st.plotly_chart(fig_packets, use_container_width=True)
        
        # Plot 2: Total bytes per session
        fig_bytes = go.Figure(
            data=[go.Bar(
                x=sessions,
                y=df['total_bytes'],
                marker_color='#10b981',
                name='Total Bytes'
            )]
        )
        fig_bytes.update_layout(
            title="Total Bytes Transferred per Session",
            xaxis_title="Session / File Name",
            yaxis_title="Bytes",
            template="plotly_dark",
            margin=dict(l=40, r=40, t=60, b=100)
        )
        st.plotly_chart(fig_bytes, use_container_width=True)
        
        # Plot 3: TCP vs UDP count comparison per session (grouped bar chart)
        fig_tcp_udp = go.Figure(
            data=[
                go.Bar(
                    x=sessions,
                    y=df['tcp_count'],
                    name='TCP Count',
                    marker_color='#f59e0b'  # amber
                ),
                go.Bar(
                    x=sessions,
                    y=df['udp_count'],
                    name='UDP Count',
                    marker_color='#8b5cf6'  # violet
                )
            ]
        )
        fig_tcp_udp.update_layout(
            title="TCP vs UDP Packet Count Comparison",
            xaxis_title="Session / File Name",
            yaxis_title="Packet Count",
            barmode='group',
            template="plotly_dark",
            margin=dict(l=40, r=40, t=60, b=100)
        )
        st.plotly_chart(fig_tcp_udp, use_container_width=True)
